/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agile;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author nancy
 */
public class s1 extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public s1() {
        initComponents();
         try {
          Class.forName("com.mysql.jdbc.Driver");
    try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HBAS","root","samyu_park")) {
        Statement stm = conn.createStatement();
        //String sql = "select Ano from student;";
        //ResultSet a =stm.executeQuery(sql);
        //String txt=Integer.toString(a);
       // String sql1 = "insert into login1 values('"+id1+"','"+name1+"')";
        //stm.executeUpdate(sql1);
        //adnum.setText(user);
        String str1=adnum.getName();
       //  System.out.println(str1);
      //   String str = adnumber.getText();
     // String str1=sstudid.getText();
/*PreparedStatement st = conn.prepareStatement("select * from stud where Ano=? ");
 
            st.setString(1, str);  
         //   st.setString(2,str1);
            //Excuting Query  
            ResultSet rs = st.executeQuery();  
            if (rs.next()) { 
                String adnum1 = rs.getString(1);
                String studname1= rs.getString(2);  
                String cla1 = rs.getString(3);  
                 String cl1 = rs.getString(4);  
                 String room1 = rs.getString(5);  
                 String place1 = rs.getString(6);  
                  String mail1 = rs.getString(7);  
                //Sets Records in TextFields. 
                adnum.setText(adnum1);
                studname.setText(studname1);
                cla.setText(cla1);
                cl.setText(cl1);
                room.setText(room1);
                place.setText(place1);
                mail.setText(mail1);
        javax.swing.JOptionPane.showMessageDialog(this,"Inserted successfully!!!");
        new Stureg().setVisible(true);
    }
         */
        //////   
        }
         }catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
           
        }    
    }

  //  private Student1(String user) {
    //    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        studname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cla = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ins = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        place = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        adnum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 5000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel3.setText("STUDENT NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 25));

        studname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studnameActionPerformed(evt);
            }
        });
        jPanel1.add(studname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 375, 30));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel8.setText("CLASS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(cla, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 370, 30));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        jLabel4.setText("YEAR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 28));
        jPanel1.add(cl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 370, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("INSTITUTE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, 25));
        jPanel1.add(ins, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 375, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("DOB");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 30));
        jPanel1.add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 370, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 620, 590));

        jLabel9.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel9.setText("STUDENT ADMISSION NUMBER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jButton3.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jButton3.setText("CLICK TO GET YOUR PROFILE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 350, -1));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, 230, 40));

        adnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adnumActionPerformed(evt);
            }
        });
        getContentPane().add(adnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 52, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
new Amain().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hbas","root","samyu_park");
            String str = adnum.getText();
            // String str1=sstudid.getText();
            PreparedStatement st = conn.prepareStatement("select * from studs3 where reg=? ");
   // PreparedStatement st1 = conn.prepareStatement("select date from travdate1 where sno=1 ");
   // PreparedStatement st1 = conn.prepareStatement("select");
            st.setString(1, str);
            //   st.setString(2,str1);
            //Excuting Query
            ResultSet rs = st.executeQuery();
            
            if (rs.next()) {
                String adnum1 = rs.getString(1);
                String studname1= rs.getString(2);
                String cla1 = rs.getString(3);
                String cl1 = rs.getString(4);
                String room1 = rs.getString(5);
               String place1 = rs.getString(6);
                //String mail1 = rs.getString(7);
                //Sets Records in TextFields.
                adnum.setText(adnum1);
                studname.setText(studname1);
                cla.setText(cla1);
                cl.setText(cl1);
                ins.setText(room1);
                place.setText(place1);
                //mail.setText(mail1);
                
//ResultSet rs1 = st1.executeQuery();
            
  /*          if (rs1.next()) {
                String date1 = rs1.getString(1);
                 date.setText(date1);
                
                
            }
*/
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Name not Found");
            }

        }catch (SQLException | ClassNotFoundException e) {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }                       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void adnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adnumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 String user = null;
              //  new Details(user).setVisible(true);
                new s1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adnum;
    private javax.swing.JTextField cl;
    private javax.swing.JTextField cla;
    private javax.swing.JTextField ins;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField place;
    private javax.swing.JTextField studname;
    // End of variables declaration//GEN-END:variables
}
